-- =============================================================================
-- 040_invoicing.sql — NO-OP / RECONCILIATION NOTE
-- =============================================================================
--
-- The Wave 34 invoicing build agent originally proposed brand-new `invoices`,
-- `invoice_lines` and `tax_profiles` tables keyed on `org_id`.  Integration
-- found that the CANONICAL schema already ships these tables:
--
--   * `invoices`      — migration 007 (payments_generic): issuer_org_id /
--                       recipient_org_id / recipient_customer_id /
--                       recipient_snapshot, issuer, vat_applied,
--                       vat_rate_percent, subtotal_cents, vat_cents,
--                       total_cents, invoice_number, pdf_object_key,
--                       idempotency_key, status, currency, due_date, …
--   * `tax_profiles`  — migration 010 (engagement): org_id (PK), legal_name,
--                       registered_address, country, vat_number,
--                       company_number, contact_email, contact_phone,
--                       vat_rate_percent.
--   * `invoice_lines` — already present alongside `invoices`.
--
-- These already have RLS enabled.  Re-creating them is both unnecessary and
-- impossible (the invented `org_id` column does not exist on the canonical
-- `invoices`), so this migration intentionally does nothing.  The invoicing
-- handler (internal/handlers/invoicing) is reconciled to the canonical columns
-- instead — see that package.
--
-- Kept as a numbered file so the migration sequence stays gap-free and the
-- ledger records that 040 ran.
SELECT 1;
