// Package customdomains provides the DB access layer for the custom_domains
// table created by migration 036_custom_domains.sql.
//
// All queries run under db.Scoped — either ServiceRoleScope (for status
// transitions from the verification path) or the caller-supplied tenant scope
// (for list/add/remove operations guarded by RLS).
package customdomains

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/beepbite/backend/internal/db"
)

// ---------------------------------------------------------------------------
// Sentinel errors
// ---------------------------------------------------------------------------

var (
	// ErrNotFound is returned when the domain row does not exist (or is
	// outside the caller's org scope).
	ErrNotFound = errors.New("custom domain not found")
	// ErrDuplicate is returned when the hostname is already registered.
	ErrDuplicate = errors.New("hostname already registered")
	// ErrNotOwner is returned when the requested domain does not belong to
	// one of the caller's locations.
	ErrNotOwner = errors.New("not authorised to manage this domain")
	// ErrAlreadyVerified is returned when verify is called on a domain that
	// is already verified/live.
	ErrAlreadyVerified = errors.New("domain is already verified")
)

// ---------------------------------------------------------------------------
// Wire types
// ---------------------------------------------------------------------------

// Domain is the DTO returned to callers (list, add, get, verify).
type Domain struct {
	ID                string     `json:"id"`
	LocationID        string     `json:"location_id"`
	Hostname          string     `json:"hostname"`
	Status            string     `json:"status"`
	VerificationToken string     `json:"verification_token"`
	VerifiedAt        *time.Time `json:"verified_at"`
	CertIssuedAt      *time.Time `json:"cert_issued_at"`
	RemovedAt         *time.Time `json:"removed_at"`
	CreatedAt         time.Time  `json:"created_at"`
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

// Store handles all DB access for the customdomains package.
type Store struct {
	pool *pgxpool.Pool
}

// NewStore constructs a Store backed by pool.
func NewStore(pool *pgxpool.Pool) *Store { return &Store{pool: pool} }

// ---------------------------------------------------------------------------
// List
// ---------------------------------------------------------------------------

// ListByLocation returns all non-removed custom_domains for locationID.
// Runs under tenant scope — the RLS SELECT policy enforces ownership.
func (s *Store) ListByLocation(ctx context.Context, scope db.Scope, locationID string) ([]Domain, error) {
	var out []Domain

	err := db.Scoped(ctx, s.pool, scope, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT id, location_id, hostname, status, verification_token,
			       verified_at, cert_issued_at, removed_at, created_at
			  FROM custom_domains
			 WHERE location_id = $1
			   AND removed_at IS NULL
			 ORDER BY created_at DESC
		`, locationID)
		if err != nil {
			return err
		}
		defer rows.Close()
		for rows.Next() {
			var d Domain
			if err := rows.Scan(
				&d.ID, &d.LocationID, &d.Hostname, &d.Status, &d.VerificationToken,
				&d.VerifiedAt, &d.CertIssuedAt, &d.RemovedAt, &d.CreatedAt,
			); err != nil {
				return err
			}
			out = append(out, d)
		}
		return rows.Err()
	})
	if err != nil {
		return nil, err
	}
	if out == nil {
		out = []Domain{}
	}
	return out, nil
}

// ---------------------------------------------------------------------------
// Add
// ---------------------------------------------------------------------------

// AddDomain inserts a new custom_domain row for locationID / hostname.
// The verification_token and default status are generated by the DB defaults.
// Runs under tenant scope so the RLS INSERT policy validates ownership.
func (s *Store) AddDomain(ctx context.Context, scope db.Scope, locationID, hostname string) (*Domain, error) {
	var d Domain

	err := db.Scoped(ctx, s.pool, scope, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			INSERT INTO custom_domains (location_id, hostname)
			VALUES ($1, $2)
			RETURNING id, location_id, hostname, status, verification_token,
			          verified_at, cert_issued_at, removed_at, created_at
		`, locationID, hostname).Scan(
			&d.ID, &d.LocationID, &d.Hostname, &d.Status, &d.VerificationToken,
			&d.VerifiedAt, &d.CertIssuedAt, &d.RemovedAt, &d.CreatedAt,
		)
	})
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23505" {
			return nil, ErrDuplicate
		}
		return nil, err
	}
	return &d, nil
}

// ---------------------------------------------------------------------------
// Get (by ID, with tenant guard)
// ---------------------------------------------------------------------------

// GetDomain returns the domain row for id, restricted to the caller's allowed
// location IDs. Returns ErrNotFound / ErrNotOwner appropriately.
// Runs under ServiceRoleScope; ownership is enforced in-process.
func (s *Store) GetDomain(ctx context.Context, id string, allowedLocationIDs []string) (*Domain, error) {
	var d Domain

	err := db.Scoped(ctx, s.pool, db.ServiceRoleScope(), func(tx pgx.Tx) error {
		err := tx.QueryRow(ctx, `
			SELECT id, location_id, hostname, status, verification_token,
			       verified_at, cert_issued_at, removed_at, created_at
			  FROM custom_domains
			 WHERE id = $1
			   AND removed_at IS NULL
		`, id).Scan(
			&d.ID, &d.LocationID, &d.Hostname, &d.Status, &d.VerificationToken,
			&d.VerifiedAt, &d.CertIssuedAt, &d.RemovedAt, &d.CreatedAt,
		)
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrNotFound
		}
		return err
	})
	if err != nil {
		return nil, err
	}

	// Tenant guard.
	allowed := false
	for _, lid := range allowedLocationIDs {
		if lid == d.LocationID {
			allowed = true
			break
		}
	}
	if !allowed {
		return nil, ErrNotOwner
	}
	return &d, nil
}

// ---------------------------------------------------------------------------
// Verify (status transition)
// ---------------------------------------------------------------------------

// MarkVerified transitions a domain from pending/verifying → verified and
// sets verified_at = now(). Runs under ServiceRoleScope because the backend
// calls this after DNS probe success — no user JWT involved.
func (s *Store) MarkVerified(ctx context.Context, id string) (*Domain, error) {
	var d Domain

	err := db.Scoped(ctx, s.pool, db.ServiceRoleScope(), func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			UPDATE custom_domains
			   SET status      = 'verified',
			       verified_at = now()
			 WHERE id = $1
			   AND status IN ('pending', 'verifying')
			   AND removed_at IS NULL
			RETURNING id, location_id, hostname, status, verification_token,
			          verified_at, cert_issued_at, removed_at, created_at
		`, id).Scan(
			&d.ID, &d.LocationID, &d.Hostname, &d.Status, &d.VerificationToken,
			&d.VerifiedAt, &d.CertIssuedAt, &d.RemovedAt, &d.CreatedAt,
		)
	})
	if errors.Is(err, pgx.ErrNoRows) {
		// Either not found or already past verifying.
		return nil, ErrAlreadyVerified
	}
	if err != nil {
		return nil, err
	}
	return &d, nil
}

// MarkCertIssuing transitions a verified domain → cert_issuing.
// Called immediately after FlyCerts.AddCert returns nil.
func (s *Store) MarkCertIssuing(ctx context.Context, id string) error {
	return db.Scoped(ctx, s.pool, db.ServiceRoleScope(), func(tx pgx.Tx) error {
		_, err := tx.Exec(ctx, `
			UPDATE custom_domains
			   SET status = 'cert_issuing',
			       cert_issued_at = now()
			 WHERE id = $1
			   AND removed_at IS NULL
		`, id)
		return err
	})
}

// MarkLive transitions a domain → live. Called when the cert is confirmed
// (or immediately after cert_issuing in stub mode).
func (s *Store) MarkLive(ctx context.Context, id string) error {
	return db.Scoped(ctx, s.pool, db.ServiceRoleScope(), func(tx pgx.Tx) error {
		_, err := tx.Exec(ctx, `
			UPDATE custom_domains
			   SET status = 'live'
			 WHERE id = $1
			   AND removed_at IS NULL
		`, id)
		return err
	})
}

// ---------------------------------------------------------------------------
// Remove (soft delete)
// ---------------------------------------------------------------------------

// RemoveDomain soft-deletes a domain by setting removed_at. The caller must
// provide allowedLocationIDs for cross-tenant guard. Runs under
// ServiceRoleScope; the in-process guard prevents cross-tenant writes.
func (s *Store) RemoveDomain(ctx context.Context, id string, allowedLocationIDs []string) error {
	// First verify ownership.
	if _, err := s.GetDomain(ctx, id, allowedLocationIDs); err != nil {
		return err
	}

	return db.Scoped(ctx, s.pool, db.ServiceRoleScope(), func(tx pgx.Tx) error {
		tag, err := tx.Exec(ctx, `
			UPDATE custom_domains
			   SET removed_at = now(),
			       status     = 'failed'
			 WHERE id = $1
			   AND removed_at IS NULL
		`, id)
		if err != nil {
			return err
		}
		if tag.RowsAffected() == 0 {
			return ErrNotFound
		}
		return nil
	})
}

// ---------------------------------------------------------------------------
// Host-resolve (used by middleware — service-role, no user context)
// ---------------------------------------------------------------------------

// ResolveCustomHostname looks up a live custom_domain by hostname and returns
// its location_id. Returns ErrNotFound when no live row matches.
// Always runs under ServiceRoleScope because it is called from the
// hostresolve middleware before any auth context is available.
func (s *Store) ResolveCustomHostname(ctx context.Context, hostname string) (string, error) {
	var locationID string

	err := db.Scoped(ctx, s.pool, db.ServiceRoleScope(), func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT location_id
			  FROM custom_domains
			 WHERE hostname   = $1
			   AND status     = 'live'
			   AND removed_at IS NULL
		`, hostname).Scan(&locationID)
	})
	if errors.Is(err, pgx.ErrNoRows) {
		return "", ErrNotFound
	}
	if err != nil {
		return "", err
	}
	return locationID, nil
}

// ResolveSlug looks up a location by slug and returns its id.
// Returns ErrNotFound when no active location matches.
// Always runs under ServiceRoleScope.
func (s *Store) ResolveSlug(ctx context.Context, slug string) (string, error) {
	var locationID string

	err := db.Scoped(ctx, s.pool, db.ServiceRoleScope(), func(tx pgx.Tx) error {
		return tx.QueryRow(ctx, `
			SELECT id
			  FROM locations
			 WHERE slug      = $1
			   AND is_active = true
		`, slug).Scan(&locationID)
	})
	if errors.Is(err, pgx.ErrNoRows) {
		return "", ErrNotFound
	}
	if err != nil {
		return "", err
	}
	return locationID, nil
}
